FROM openeuler/openeuler:24.03-lts

RUN dnf update -y && \
    dnf install -y \
        python3 python3-pip \
        gcc gcc-c++ make cmake \
        wget git tar gzip unzip \
        qemu-system-aarch64 \
    && dnf clean all

RUN pip3 install --upgrade pip && \
    pip3 install \
        typer \
        pydantic \
        jinja2 \
        psutil \
        onnx \
        onnxruntime \
        onnxsim \
        numpy \
        pillow \
        opencv-python

WORKDIR /workspace
